##### CORE #####
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

set -g default-shell /usr/bin/fish

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",alacritty:RGB"

set -g history-limit 10000
set -s escape-time 0
set -g mouse on

set -g status on
set -g status-interval 10
set -g status-left-length 100
set -g status-right-length 100


##### TPM + PLUGINS #####
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'rose-pine/tmux'

set -g @rose_pine_variant 'moon' # Options are 'main', 'moon' or 'dawn'

##### YANK #####
set -g @yank_selection 'clipboard'
set -g @yank_selection_mouse 'clipboard'


##### ATALHOS #####
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

bind -n M-v select-layout even-vertical
bind -n M-h select-layout even-horizontal

bind S setw synchronize-panes
bind r source-file ~/.tmux.conf \; display "Configuração recarregada!"


# Navegação com Alt (Meta)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

##### TPM (SEMPRE ÚLTIMO) #####
run '~/.tmux/plugins/tpm/tpm'

