monitor.bluez.rules = [
  {
    matches = [
      {
        node.name = "~bluez_output.*"
      }
    ],
    actions = {
      update-props = {
        "channelmix.max-volume": 0.6,
        "bluez5.hw-volume": [ ]
      }
    }
  }
]

