$mainMod = SUPER

$terminal = prime-run alacritty
$fileManager = dolphin
$menu = wofi --show drun
$browser = prime-run brave

misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = false
}
