general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    resize_on_border = false
    allow_tearing = false
    layout = dwindle

    # col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    # col.inactive_border = rgba(595959aa)

    col.active_border = rgba(d79921ee) rgba(b57614ee) 45deg
    col.inactive_border = rgba(3c3836aa)
}

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}
